'''velocidade_km_por_hora=100
velocidade_km_por_min = velocidade_km_por_hora/60.00
print("v =", format(velocidade_km_por_min, '.2f'), 'km/min')'''
a = 7
b = 3
print("a // b =", a // b)
print("-a // b =", -a // b)
print("a // -b =", a // -b)
print("-a // -b =", -a // -b)